docs_dir: docs
markdown_extensions:
- admonition
pages:
- 项目详情: 项目详情.md
- 玩法介绍: 玩法介绍.md
- 工具使用: 工具使用.md
- 资源规范: 资源规范.md
- 代码规范: 代码规范.md
- 教程地址: 教程地址.md
- 扩展插件: 扩展插件.md
- API: []
repo_url: https://github.com/vmjcv/journey_in_world/
site_name: journey_in_world
theme: material
