class_name Config

const VERSION_MAJOR					:= 0
const VERSION_MINOR					:= 4
const VERSION_PATCH					:= 0
const VERSION_STATUS				:= "-dev"
const VERSION_STRING				:= "%d.%d.%d%s" % [VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, VERSION_STATUS]
const CONFIG_PATH 					:= "user://settings.cfg"
const DEFAULT_FOREGROUND_FPS 		:= 144
const DEFAULT_BACKGROUND_FPS		:= 10
const HIDE_PLAYER_NAME				:= false
const GAME_LANGUAGE					:= null
const USE_2D						:= true
const CAMERA_SHAKE					:= true
const COLOR_BLINDNESS_MODE			:= Types.ColorBlindnessMode.DEFAULT
const USER_INTERFACE_SIZE			:= Types.UserInterfaceSize.DEFAULT
const GAME_SPEED					:= Types.GameSpeed.DEFAULT
const BATTLE_PREVIEW				:= true
const INPUT_MAP						:= null
const IMAGE_QUALITY					:= true
const RESOLUTION					:= Types.Resolution.DEFAULT
const DISPLAY_MODE					:= Types.DisplayMode.BORDER
const AUDIO_SFX						:= 50
const AUDIO_MUSIC					:= 50
const AUDIO_MASTER					:= 50
const FANCY_MOVEMENT				:= true
const OVAL_HAND_SHAPE				:= true
const CARD_PREVIEW					:= Types.CardPreview.SCALING_VIEWPORT
const USE_DEBUG						:= false
