# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
tool
class_name LocalizationKeys

const ABOUT_DIALOG_TITLE = "ABOUT_DIALOG_TITLE"
const ABOUT_DIALOG_COPYRIGHT = "ABOUT_DIALOG_COPYRIGHT"
const ABOUT_DIALOG_LICSENSE = "ABOUT_DIALOG_LICSENSE"
const ABOUT_DIALOG_BASED_ON = "ABOUT_DIALOG_BASED_ON"
const GAME_TITLE = "GAME_TITLE"
const ABOUT_DIALOG_SET_IN = "ABOUT_DIALOG_SET_IN"
const EXIT_DIALOG_TITLE = "EXIT_DIALOG_TITLE"
const EXIT_DIALOG_TEXT = "EXIT_DIALOG_TEXT"
const EXIT = "EXIT"
const CANCEL = "CANCEL"

const KEYS = [
 "ABOUT_DIALOG_TITLE",
 "ABOUT_DIALOG_COPYRIGHT",
 "ABOUT_DIALOG_LICSENSE",
 "ABOUT_DIALOG_BASED_ON",
 "GAME_TITLE",
 "ABOUT_DIALOG_SET_IN",
 "EXIT_DIALOG_TITLE",
 "EXIT_DIALOG_TEXT",
 "EXIT",
 "CANCEL"
]