# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
tool
class_name LocalizationKeys

const ABOUT_DIALOG_TITLE = "ABOUT_DIALOG_TITLE"
const ABOUT_DIALOG_COPYRIGHT = "ABOUT_DIALOG_COPYRIGHT"
const ABOUT_DIALOG_LICSENSE = "ABOUT_DIALOG_LICSENSE"
const ABOUT_DIALOG_BASED_ON = "ABOUT_DIALOG_BASED_ON"
const GAME_TITLE = "GAME_TITLE"
const ABOUT_DIALOG_SET_IN = "ABOUT_DIALOG_SET_IN"
const EXIT_DIALOG_TITLE = "EXIT_DIALOG_TITLE"
const EXIT_DIALOG_TEXT = "EXIT_DIALOG_TEXT"
const EXIT = "EXIT"
const CANCEL = "CANCEL"
const AUDIO = "AUDIO"
const GRAPHICS = "GRAPHICS"
const GAME_PLAY = "GAME_PLAY"
const EXTRA_FEATURES = "EXTRA_FEATURES"
const OTHER = "OTHER"
const LANGUAGE = "LANGUAGE"
const SETTING_LANGUAGE_ZH = "SETTING_LANGUAGE_ZH"
const SETTING_LANGUAGE_EN = "SETTING_LANGUAGE_EN"
const HIDE_PLAYER_NAME = "HIDE_PLAYER_NAME"
const USE_2D = "USE_2D"
const CAMERA_SHAKE = "CAMERA_SHAKE"
const COLOR_BLINDNESS_MODE = "COLOR_BLINDNESS_MODE"
const USER_INTERFACE_SIZE = "USER_INTERFACE_SIZE"
const COLOR_BLINDNESS_MODE_DEFAULT = "COLOR_BLINDNESS_MODE_DEFAULT"
const COLOR_BLINDNESS_MODE_GREEN = "COLOR_BLINDNESS_MODE_GREEN"
const USER_INTERFACE_SIZE_DEFAULT = "USER_INTERFACE_SIZE_DEFAULT"
const USER_INTERFACE_SIZE_BIG = "USER_INTERFACE_SIZE_BIG"
const GAME_SPEED_DEFAULT = "GAME_SPEED_DEFAULT"
const GAME_SPEED_SMALL = "GAME_SPEED_SMALL"
const GAME_SPEED_MIDDLE = "GAME_SPEED_MIDDLE"
const GAME_SPEED_BIG = "GAME_SPEED_BIG"
const GAME_SPEED = "GAME_SPEED"
const BATTLE_PREVIEW = "BATTLE_PREVIEW"

const KEYS = [
 "ABOUT_DIALOG_TITLE",
 "ABOUT_DIALOG_COPYRIGHT",
 "ABOUT_DIALOG_LICSENSE",
 "ABOUT_DIALOG_BASED_ON",
 "GAME_TITLE",
 "ABOUT_DIALOG_SET_IN",
 "EXIT_DIALOG_TITLE",
 "EXIT_DIALOG_TEXT",
 "EXIT",
 "CANCEL",
 "AUDIO",
 "GRAPHICS",
 "GAME_PLAY",
 "EXTRA_FEATURES",
 "OTHER",
 "LANGUAGE",
 "SETTING_LANGUAGE_ZH",
 "SETTING_LANGUAGE_EN",
 "HIDE_PLAYER_NAME",
 "USE_2D",
 "CAMERA_SHAKE",
 "COLOR_BLINDNESS_MODE",
 "USER_INTERFACE_SIZE",
 "COLOR_BLINDNESS_MODE_DEFAULT",
 "COLOR_BLINDNESS_MODE_GREEN",
 "USER_INTERFACE_SIZE_DEFAULT",
 "USER_INTERFACE_SIZE_BIG",
 "GAME_SPEED_DEFAULT",
 "GAME_SPEED_SMALL",
 "GAME_SPEED_MIDDLE",
 "GAME_SPEED_BIG",
 "GAME_SPEED",
 "BATTLE_PREVIEW"
]