# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
tool
class_name LocalizationKeys

const ABOUT_DIALOG_TITLE = "ABOUT_DIALOG_TITLE"
const ABOUT_DIALOG_COPYRIGHT = "ABOUT_DIALOG_COPYRIGHT"
const ABOUT_DIALOG_LICSENSE = "ABOUT_DIALOG_LICSENSE"
const ABOUT_DIALOG_BASED_ON = "ABOUT_DIALOG_BASED_ON"
const GAME_TITLE = "GAME_TITLE"
const ABOUT_DIALOG_SET_IN = "ABOUT_DIALOG_SET_IN"
const EXIT_DIALOG_TITLE = "EXIT_DIALOG_TITLE"
const EXIT_DIALOG_TEXT = "EXIT_DIALOG_TEXT"
const EXIT = "EXIT"
const CANCEL = "CANCEL"
const AUDIO = "AUDIO"
const GRAPHICS = "GRAPHICS"
const GAME_PLAY = "GAME_PLAY"
const EXTRA_FEATURES = "EXTRA_FEATURES"
const OTHER = "OTHER"
const LANGUAGE = "LANGUAGE"
const SETTING_LANGUAGE_ZH = "SETTING_LANGUAGE_ZH"
const SETTING_LANGUAGE_EN = "SETTING_LANGUAGE_EN"
const HIDE_PLAYER_NAME = "HIDE_PLAYER_NAME"
const USE_2D = "USE_2D"
const CAMERA_SHAKE = "CAMERA_SHAKE"
const COLOR_BLINDNESS_MODE = "COLOR_BLINDNESS_MODE"
const USER_INTERFACE_SIZE = "USER_INTERFACE_SIZE"
const COLOR_BLINDNESS_MODE_DEFAULT = "COLOR_BLINDNESS_MODE_DEFAULT"
const COLOR_BLINDNESS_MODE_GREEN = "COLOR_BLINDNESS_MODE_GREEN"
const USER_INTERFACE_SIZE_DEFAULT = "USER_INTERFACE_SIZE_DEFAULT"
const USER_INTERFACE_SIZE_BIG = "USER_INTERFACE_SIZE_BIG"
const GAME_SPEED_DEFAULT = "GAME_SPEED_DEFAULT"
const GAME_SPEED_SMALL = "GAME_SPEED_SMALL"
const GAME_SPEED_MIDDLE = "GAME_SPEED_MIDDLE"
const GAME_SPEED_BIG = "GAME_SPEED_BIG"
const GAME_SPEED = "GAME_SPEED"
const BATTLE_PREVIEW = "BATTLE_PREVIEW"
const SHORTCUT_KEY = "SHORTCUT_KEY"
const OPEN_OR_CLOSE = "OPEN_OR_CLOSE"
const RESET_SHORTCUT_KEY = "RESET_SHORTCUT_KEY"
const CARD1 = "CARD1"
const CARD2 = "CARD2"
const CARD3 = "CARD3"
const CARD4 = "CARD4"
const CARD5 = "CARD5"
const TOGGLE_GAME_SPEED = "TOGGLE_GAME_SPEED"
const USE_CARD = "USE_CARD"
const CANCEL_USE_CARD = "CANCEL_USE_CARD"
const SETTING = "SETTING"
const LEFT = "LEFT"
const RIGHT = "RIGHT"
const UP = "UP"
const DOWN = "DOWN"
const SHOW_CARDS = "SHOW_CARDS"
const SHOW_DRAW_CARDS = "SHOW_DRAW_CARDS"
const SHOW_DISCARD_CARDS = "SHOW_DISCARD_CARDS"
const SHOW_SHORTCUT_KEY = "SHOW_SHORTCUT_KEY"
const SHOW_MAP = "SHOW_MAP"
const ADD_NEW_CONTROLS = "ADD_NEW_CONTROLS"
const KEY_BOARD = "KEY_BOARD"
const IMAGE_QUALITY = "IMAGE_QUALITY"
const RESOLUTION = "RESOLUTION"
const DISPLAY_MODE = "DISPLAY_MODE"
const DISPLAY_MODE_BORDER = "DISPLAY_MODE_BORDER"
const DISPLAY_MODE_FULLSCREEN = "DISPLAY_MODE_FULLSCREEN"
const DISPLAY_MODE_BORDERLESS = "DISPLAY_MODE_BORDERLESS"
const AUDIO_SFX = "AUDIO_SFX"
const AUDIO_MUSIC = "AUDIO_MUSIC"
const AUDIO_MASTER = "AUDIO_MASTER"

const KEYS = [
 "ABOUT_DIALOG_TITLE",
 "ABOUT_DIALOG_COPYRIGHT",
 "ABOUT_DIALOG_LICSENSE",
 "ABOUT_DIALOG_BASED_ON",
 "GAME_TITLE",
 "ABOUT_DIALOG_SET_IN",
 "EXIT_DIALOG_TITLE",
 "EXIT_DIALOG_TEXT",
 "EXIT",
 "CANCEL",
 "AUDIO",
 "GRAPHICS",
 "GAME_PLAY",
 "EXTRA_FEATURES",
 "OTHER",
 "LANGUAGE",
 "SETTING_LANGUAGE_ZH",
 "SETTING_LANGUAGE_EN",
 "HIDE_PLAYER_NAME",
 "USE_2D",
 "CAMERA_SHAKE",
 "COLOR_BLINDNESS_MODE",
 "USER_INTERFACE_SIZE",
 "COLOR_BLINDNESS_MODE_DEFAULT",
 "COLOR_BLINDNESS_MODE_GREEN",
 "USER_INTERFACE_SIZE_DEFAULT",
 "USER_INTERFACE_SIZE_BIG",
 "GAME_SPEED_DEFAULT",
 "GAME_SPEED_SMALL",
 "GAME_SPEED_MIDDLE",
 "GAME_SPEED_BIG",
 "GAME_SPEED",
 "BATTLE_PREVIEW",
 "SHORTCUT_KEY",
 "OPEN_OR_CLOSE",
 "RESET_SHORTCUT_KEY",
 "CARD1",
 "CARD2",
 "CARD3",
 "CARD4",
 "CARD5",
 "TOGGLE_GAME_SPEED",
 "USE_CARD",
 "CANCEL_USE_CARD",
 "SETTING",
 "LEFT",
 "RIGHT",
 "UP",
 "DOWN",
 "SHOW_CARDS",
 "SHOW_DRAW_CARDS",
 "SHOW_DISCARD_CARDS",
 "SHOW_SHORTCUT_KEY",
 "SHOW_MAP",
 "ADD_NEW_CONTROLS",
 "KEY_BOARD",
 "IMAGE_QUALITY",
 "RESOLUTION",
 "DISPLAY_MODE",
 "DISPLAY_MODE_BORDER",
 "DISPLAY_MODE_FULLSCREEN",
 "DISPLAY_MODE_BORDERLESS",
 "AUDIO_SFX",
 "AUDIO_MUSIC",
 "AUDIO_MASTER"
]